# Generated by Django 3.2.3 on 2021-05-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('THG', '0004_blogcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msgid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
